#include "serve.h"
#include "serve_internal.h"

#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <thread>
#include <vector>

#include <httplib.h>

#include "http_api.h"
#include "contract.h"
#include "out.h"
#include "util.h"
#include "version.h"

#ifdef _WIN32
#include <bcrypt.h>
#include <windows.h>
#pragma comment(lib, "bcrypt.lib")
#else
#include <fcntl.h>
#include <fstream>
#include <sys/file.h>
#include <unistd.h>
#endif

namespace dsvc {

namespace {

#ifdef _WIN32
volatile LONG g_ctrl = 0;
BOOL WINAPI ctrl_handler(DWORD) {
    InterlockedExchange(&g_ctrl, 1);
    return TRUE;
}
void install_signal_handlers() { SetConsoleCtrlHandler(ctrl_handler, TRUE); }
#else
volatile sig_atomic_t g_ctrl = 0;
void sig_handler(int) { g_ctrl = 1; }
void install_signal_handlers() {
    std::signal(SIGINT, sig_handler);
    std::signal(SIGTERM, sig_handler);
}
#endif

std::string gen_token() {
    unsigned char buf[32];
#ifdef _WIN32
    NTSTATUS st =
        BCryptGenRandom(nullptr, buf, sizeof(buf), BCRYPT_USE_SYSTEM_PREFERRED_RNG);
    if (st != 0) {
        uint64_t x = (uint64_t)GetTickCount64();  // крайний, небезопасный фолбэк
        for (size_t i = 0; i < sizeof(buf); i++) {
            x = x * 6364136223846793005ULL + 1442695040888963407ULL;
            buf[i] = (unsigned char)(x >> 56);
        }
    }
#else
    std::ifstream f("/dev/urandom", std::ios::binary);
    if (f) f.read((char*)buf, sizeof(buf));
    else memset(buf, 0, sizeof(buf));
#endif
    static const char* hex = "0123456789abcdef";
    std::string out;
    out.reserve(sizeof(buf) * 2);
    for (size_t i = 0; i < sizeof(buf); i++) {
        out.push_back(hex[buf[i] >> 4]);
        out.push_back(hex[buf[i] & 0xF]);
    }
    return out;
}

std::string discovery_path(const std::string& override_path) {
    if (!override_path.empty()) return override_path;
    if (const char* e = std::getenv("LLAO_DISCOVERY")) {
        if (*e) return e;
    }
#ifdef _WIN32
    const char* la = std::getenv("LOCALAPPDATA");
    std::string base = la ? la : ".";
    return util::join_path(util::join_path(base, "llao"), "daemon.json");
#else
    const char* xdg = std::getenv("XDG_DATA_HOME");
    const char* home = std::getenv("HOME");
    std::string base = xdg ? xdg : (home ? std::string(home) + "/.local/share" : "/tmp");
    return util::join_path(util::join_path(base, "llao"), "daemon.json");
#endif
}

bool write_discovery(const std::string& path, const nlohmann::json& j) {
    if (path.empty()) return false;
    util::mkdirs(util::dir_name(path));
    std::string tmp = path + ".tmp";
    if (!util::write_text(tmp, j.dump())) return false;
    util::ReplaceResult rr = util::replace_file(path, tmp);
    if (!rr.ok) {
        // Неудачная замена: кандидат остался в tmp (резервная копия данных).
        // Прибираем его только если replace_file сохранил копию не в tmp
        // (здесь этого не происходит) — иначе висящий tmp удалён бы не был.
        if (!rr.backup.empty() && rr.backup != tmp) util::remove_file(tmp);
        return false;
    }
    return true;
}

void print_help() {
    // Английский — базовый текст, русский живёт в lang/ru.json по тем же ключам.
    out::print("LLAO server — headless engine with HTTP API and web UI\n");
    out::print("\n");
    out::print("Usage: llao serve [options]\n");
    out::print("\n");
    out::print("Session options (optimization defaults):\n");
    out::print("  --jobs N|M.M          thread count or core multiplier (default 2.0)\n");
    out::print("  --verify MODE         all|winner (default all)\n");
    out::print("  --ignore-errors       do not abort a file because of a variant failure: skip\n"
                "                        the variant, and if the winner fails verification —\n"
                "                        fall through to the next candidates (default: off,\n"
                "                        strict mode)\n");
    out::print("  --dry-run             do not write the result\n");
    out::print("  --no-download         do not download codecs (the startup gate only checks)\n");
    out::print("  --no-stats            do not accumulate stats.json\n");
    out::print("  --update-codecs       update the codecs to their latest versions before\n");
    out::print("                        starting, and refuse to start if any of them fails\n");
    out::print("  --debug               runs/*.jsonl log + debugging\n");
    out::print("  --report PATH         final report on shutdown\n");
    out::print("  --restore-to ID       target format of the restore mode (default flac)\n");
    out::print("\n");
    out::print("Server:\n");
    out::print("  --bind ADDR           listening address (default 0.0.0.0)\n");
    out::print("  --port N              port (default 18180); 0 = pick a free one\n");
    out::print("  --token HEX           explicit token (generated by default)\n");
    out::print("  --no-auth             disable authorization (debugging only!)\n");
    out::print("  --discovery PATH      discovery file path (default: %%LOCALAPPDATA%%/llao/daemon.json)\n");
    out::print("\n");
    out::print("  --help                this help\n");
}

}  // namespace

int run_daemon(const std::vector<std::string>& args) {
    dsvc::install_signal_handlers();

#ifdef _WIN32
    // Одиночный экземпляр демона. Именованный мьютекс в пространстве «Local\»
    // (одна копия на сессию пользователя): вторая копия на другом порту будет
    // отвергнута, чтобы не делить tmp-каталог и очередь. Handle держим до
    // выхода — при завершении процесса ОС сама освободит имя.
    HANDLE singleton = CreateMutexW(nullptr, FALSE, L"Local\\llao-singleton");
    if (!singleton) {
        std::fprintf(stderr, "ERROR: could not create singleton mutex (error %lu)\n",
                     (unsigned long)GetLastError());
        return 1;
    }
    if (GetLastError() == ERROR_ALREADY_EXISTS) {
        std::fprintf(stderr, "ERROR: another LLAO server is already running\n");
        CloseHandle(singleton);
        return 1;
    }
    (void)singleton;  // живёт до завершения процесса; закрытие — за ОС
#else
    // Тот же запрет для нативной сборки. Раньше он жил только в ветке выше,
    // и `llao-linux serve` можно было поднять сколько угодно копий: они
    // делили каталог сессий и очередь, и это выглядело как поломка кодеков
    // («wavpack: can't open file ref.wav») на совершенно обычных файлах.
    // Имя мьютекса Windows привязано к сессии пользователя, поэтому здесь —
    // блокировка файла на пользователя: flock держится, пока живёт процесс,
    // и освобождается сам при его завершении.
    if (const char* allow = std::getenv("LLAO_ALLOW_MULTIPLE");
        allow && *allow && std::strcmp(allow, "0") != 0) {
        std::fprintf(stderr,
                     "WARNING: LLAO_ALLOW_MULTIPLE is set — the singleton check is "
                     "off, temporary directories and the queue are not protected\n");
    } else {
        const char* rt = std::getenv("XDG_RUNTIME_DIR");
        std::string base = (rt && *rt) ? rt : "/tmp";
        char name[64];
        std::snprintf(name, sizeof(name), "/llao-singleton-%u",
                      (unsigned)getuid());
        const std::string lock_path = base + name;
        int fd = ::open(lock_path.c_str(), O_RDWR | O_CREAT | O_CLOEXEC, 0600);
        if (fd < 0) {
            // Не смогли взять блокировку — не запрещаем запуск, но говорим.
            std::fprintf(stderr,
                         "WARNING: could not open the singleton lock '%s' "
                         "(another server may be running)\n",
                         lock_path.c_str());
        } else if (::flock(fd, LOCK_EX | LOCK_NB) != 0) {
            std::fprintf(stderr, "ERROR: another LLAO server is already running\n");
            ::close(fd);
            return 1;
        } else {
            // fd держим до конца процесса — блокировка снимется сама.
            static int g_singleton_fd = fd;
            (void)g_singleton_fd;
        }
    }
#endif

    // По умолчанию слушаем все интерфейсы (0.0.0.0) — веб-интерфейс доступен
    // с других машин локальной сети. Авторизация (токен) включена по умолчанию:
    // без неё только --no-auth для отладки. Порт по умолчанию 18180.
    std::string bind = "0.0.0.0";
    int port = 18180;
    std::string token;
    bool no_auth = false;
    bool update_codecs = false;  // отладка: выключить Bearer-авторизацию
    std::string discovery_override;
    std::string restore_to = "flac";  // целевой формат режима восстановления
    optimize::Options opts;
    opts.mode = optimize::SessionMode::Daemon;
    // Демон по умолчанию нетерпим к ошибкам, как и CLI: проверяются все
    // варианты (verify=all), и сбой любого из них прерывает файл. Прежний
    // дефолт winner проверял только победителя, а сбой промежуточного варианта
    // просто исключал его из отбора — на прогоне реальной библиотеки это
    // выглядело как «файл обработан», хотя половина кандидатов отвалилась по
    // причинам, которые никто не видел. Тихая потеря кандидата в конкурсе тем
    // хуже, что следующий формат может оказаться больше победителя и быть
    // отдан неправильно. --verify=winner возвращает быстрый режим.
    opts.verify = optimize::Verify::All;

    for (size_t i = 1; i < args.size(); i++) {
        const std::string& a = args[i];
        auto next = [&]() -> std::string { return i + 1 < args.size() ? args[++i] : std::string(); };
        if (a == "--help" || a == "-h") {
            dsvc::print_help();
            return 0;
        } else if (a == "--bind") bind = next();
        else if (a == "--port") port = std::atoi(next().c_str());
        else if (a == "--token") token = next();
        else if (a == "--no-auth") no_auth = true;
        else if (a == "--discovery") discovery_override = next();
        else if (a == "--jobs") {
            std::string v = next();
            opts.jobs = std::atof(v.c_str());
            opts.jobs_float = v.find('.') != std::string::npos;
        } else if (a == "--verify" || a.rfind("--verify=", 0) == 0) {
            // Принимаются обе формы, как в CLI: `--verify winner` и
            // `--verify=winner`. Раньше `=`-форма не распознавалась и демон
            // падал с «unknown option» на ровно том написании, что показано в
            // README для optimize.
            bool ok = false;
            std::string mode = (a.rfind("--verify=", 0) == 0) ? a.substr(9) : next();
            opts.verify = dsvc::parse_verify(mode, &ok);
            if (!ok) {
                std::fprintf(stderr, "ERROR: bad --verify (all|winner)\n");
                return 1;
            }
        } else if (a == "--ignore-errors") opts.ignore_errors = true;
        else if (a == "--dry-run") opts.dry_run = true;
        else if (a == "--no-download") opts.no_download = true;
        else if (a == "--no-stats") opts.no_stats = true;
        else if (a == "--update-codecs") update_codecs = true;
        else if (a == "--debug") opts.debug = true;
        else if (a == "--report") opts.report_path = next();
        else if (a == "--restore-to") restore_to = next();
        else {
            if (a == "serve") continue;
            std::fprintf(stderr, "ERROR: unknown option: %s\n", a.c_str());
            dsvc::print_help();
            return 1;
        }
    }

    dsvc::EventBuffer events;
    dsvc::StateMirror state;
    dsvc::DaemonSession session(std::move(opts), &events, &state, restore_to, update_codecs);

    // Персистентность очереди: queue.json рядом с discovery-файлом.
    std::string disc = dsvc::discovery_path(discovery_override);
    session.set_persist_path(util::join_path(util::dir_name(disc), "queue.json"));

    std::string err;
    if (int rc = session.start(&err); rc != 0) {
        std::fprintf(stderr, "ERROR: init: %s\n", err.c_str());
        return rc;
    }

    // Восстановление очереди из queue.json (после start, до первого RPC).
    session.load_persisted(&err);
    if (!err.empty())
        std::fprintf(stderr, "WARNING: restore queue: %s\n", err.c_str());

    if (no_auth) {
        // Отладочный режим: авторизация выключена, токен не генерируется.
        // http_api разрешает все запросы при пустом токене.
        token.clear();
        out::error("WARNING: authorization disabled (--no-auth), debugging only!\n");
    } else if (token.empty()) {
        token = dsvc::gen_token();
    }
    session.set_token(token);

    httplib::Server svr;
    // Единичная привязка: либо фиксированный порт, либо авто (0 -> свободный).
    if (port > 0) {
        if (!svr.bind_to_port(bind, port)) {
            std::fprintf(stderr, "ERROR: could not bind %s:%d\n", bind.c_str(), port);
            return 1;
        }
    } else {
        port = svr.bind_to_any_port(bind);
    }
    dsvc::ApiContext ctx;
    ctx.daemon = &session;
    ctx.events = &events;
    ctx.state = &state;
    ctx.token = token;
    dsvc::mount(svr, ctx);

    session.set_on_shutdown([&] { svr.stop(); });

    // Discovery-файл (порт известен после bind).
    std::string pid = util::process_id();
    nlohmann::json dj = {{"port", port},
                         {"token", token},
                         {"pid", pid},
                         {"version", LLAO_VERSION}};
    bool disc_ok = dsvc::write_discovery(disc, dj);
    if (!disc_ok)
        std::fprintf(stderr, "WARNING: could not write discovery file %s\n", disc.c_str());
    std::fprintf(stdout, "LLAO server %s listening on %s:%d (pid %s)\n",
                  LLAO_VERSION, bind.c_str(), port, pid.c_str());
    if (no_auth)
        std::fprintf(stdout, "Auth: disabled (--no-auth)\n");
    else
        std::fprintf(stdout, "Token: %s\n", token.c_str());
    if (disc_ok) std::fprintf(stdout, "Discovery: %s\n", disc.c_str());
    if (bind == "0.0.0.0") {
        std::fprintf(stderr,
                     "WARNING: демон слушает на всех интерфейсах (0.0.0.0) — "
                     "доступен из сети. Убедитесь, что токен надёжен.\n");
    }
    std::fflush(stdout);

    // Следящий поток: обработчик сигнала только ставит g_ctrl, а httplib
    // блокируется в accept и опросить флаг там негде. Без этого перевода
    // llao-linux serve не гасился ни по Ctrl-C, ни по SIGTERM (а значит и по
    // systemctl stop / kill): демон продолжал слушать порт, пока его не
    // убьют SIGKILL. Регресс — с момента разбиения serve.cpp на модули.
    //
    // Поток выходит и по сигналу, и когда сервер остановился иначе (RPC
    // shutdown): иначе join() ждал бы вечно — g_ctrl при этом не выставлен.
    std::atomic<bool> listener_done{false};
    std::thread ctrl_watcher([&svr, &listener_done] {
        while (!g_ctrl && !listener_done.load())
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
        if (g_ctrl) svr.stop();
    });

    // Блокирующий приём. svr.stop() (по RPC shutdown или по сигналу) прерывает
    // listen и возвращает управление; после возврата выполняем graceful shutdown.
    svr.listen_after_bind();
    listener_done.store(true);

    // Остановить приём; подождать активные файлы; финализировать.
    svr.stop();
    ctrl_watcher.join();
    if (!disc.empty()) util::remove_file(disc);

    session.shutdown();
    std::fprintf(stdout, "LLAO server stopped\n");
    return 0;
}

}  // namespace dsvc
